apiVersion: v1
kind: Service
metadata: 
  name: client
  labels:
    app: client
    visualize: "true"
spec:   
  ports:
    # the port that this service should serve on
    - port: 80
      name: http
      protocol: TCP
      targetPort: 8080
  # label keys and values that must match in order to receive traffic for this service
  selector: 
    app: client
